/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-01-13 12:22:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Tourist a Travel Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>\r\n");
      out.write("<!-- custom-theme -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Tourist a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"web/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /><!-- bootstrap-css -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"web/css/owl.carousel.css\" rel=\"stylesheet\"><!-- Owl-carousel-CSS -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"web/css/popup-box.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /><!-- pop-up css --> \r\n");
      out.write("\r\n");
      out.write("<link href=\"web/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!-- banner css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"web/css/poposlides.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- //banner css -->\r\n");
      out.write("\r\n");
      out.write("<!-- font-awesome-icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"web/css/font-awesome.min.css\" />\r\n");
      out.write("<!-- //font-awesome-icons -->\r\n");
      out.write("\r\n");
      out.write("<!-- google fonts -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //google fonts -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-fixed-top\">\r\n");
      out.write(" \r\n");
      out.write("<!--/main-header-->\r\n");
      out.write("<div class=\"demo-inner-content\" id=\"home\">\r\n");
      out.write("\t<div class=\"main_agileits\">\r\n");
      out.write("\t<!--/banner-info-->\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t\t<div class=\"header-w3layouts\"> \r\n");
      out.write("\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-default navbar-fixed-top\"> \r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-header page-scroll\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">Tourist</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<h1><a class=\"navbar-brand\" href=\"index.html\">Tourist</a></h1>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right cl-effect-15\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Hidden li included to remove active class from about link when scrolled up past about section -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"hidden\"><a class=\"page-scroll\" href=\"#page-top\"></a>\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"#home\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"#packages\">Packages</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"#testimonials\">Testimonials</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"#stats\">Stats</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"page-scroll scroll\" href=\"Login\">Login/SignUp</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container -->\r\n");
      out.write("\t\t\t</nav>  \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- //header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- banner info-->\r\n");
      out.write("\t\t<div class=\"w3-banner-head-info\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t   <div class=\"banner-text\">\r\n");
      out.write("\t\t\t\t   <span class=\"fa fa-plane\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"editContent\">Travel Tourist</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Donec rutrum lacinia consequat. Nunc id dui vitae urna tincidunt varius.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"book-form\">\r\n");
      out.write("\t\t\t\t\t\t   <form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3 form-time-w3layouts editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"editContent\"><span class=\"fa fa-user\" aria-hidden=\"true\"></span> Traveller Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Name\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3 form-date-w3-agileits editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"editContent\"><span class=\"fa fa-map-marker\" aria-hidden=\"true\"></span> Travel place</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>London</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>Paris</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>India</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>Japan</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>America</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2 form-left-agileits-w3layouts editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"editContent\"><span class=\"fa fa-bus\" aria-hidden=\"true\"></span> Trip in</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"date has Datepicker\" id=\"datepicker\" name=\"Text\" type=\"text\" value=\"Start Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '21/11/2017';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2 form-left-agileits-w3layouts editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"editContent\"><span class=\"fa fa-bus\" aria-hidden=\"true\"></span> Trip out</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"agileits_w3layouts_main_gridl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"date has Datepicker\" id=\"datepicker1\" name=\"Text\" type=\"text\" value=\"Return Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '21/11/2017';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2 form-left-agileits-submit editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <input type=\"submit\" value=\"Send\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //banner-info-->\r\n");
      out.write("\t\t<div class=\"slides-box\">\r\n");
      out.write("\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t<li style=\"background: url(web/images/s1.jpg) no-repeat;background-size:cover;\"></li>\r\n");
      out.write("\t\t\t\t<li style=\"background: url(web/images/s2.jpg) no-repeat;background-size:cover;\"></li>\r\n");
      out.write("\t\t\t\t<li style=\"background: url(web/images/s3.jpg) no-repeat;background-size:cover;\"></li>\r\n");
      out.write("\t\t\t\t<li style=\"background: url(web/images/s4.jpg) no-repeat;background-size:cover;\"></li>\r\n");
      out.write("\t\t\t\t<li style=\"background: url(web/images/s5.jpg) no-repeat;background-size:cover;\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //banner  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <!--/banner-section-->\r\n");
      out.write("\r\n");
      out.write("<!-- about --> \r\n");
      out.write("<div class=\"w3ls-section w3-about\" id=\"about\">\r\n");
      out.write("\t<div class=\"container\">  \r\n");
      out.write("\t\t<div class=\"w3ls-title\"> \r\n");
      out.write("\t\t\t<h3 class=\"title\">About us</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 about-top\">\r\n");
      out.write("\t\t\t\t<h4>Welcome to travel tourist</h4>\r\n");
      out.write("\t\t\t\t<h5>travel tourist</h5>\r\n");
      out.write("\t\t\t\t<p>Pellentesque accumsan cursus dui, sodales blandit urna sodales vitae Pellentesque accumsan cursus dui, sodales blandit urna urna sodales vitae ipsum Pellentesque accumsan cursus dui, sodales blan urna sodales vitaePellentesque accumsan cursus dui, sodales blan sodales vitae.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"button button--nina\" data-text=\"Learn more\" data-toggle=\"modal\" data-target=\"#myModal\">Read More</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 middle-img\">\r\n");
      out.write("\t\t\t\t<img src=\"web/images/package1.jpg\" alt=\"about image\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 about-top last\">\r\n");
      out.write("\t\t\t\t<h4>Watch our recent video trip by travel tourist</h4>\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<a class=\"#\" data-toggle=\"modal\" data-target=\"#myModal1\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-play-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Modal5 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"myModal1\" tabindex=\"-1\" role=\"dialog\" >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <iframe src=\"https://player.vimeo.com/video/88224399\"></iframe>\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<iframe src=\"https://player.vimeo.com/video/92884601\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //Modal5 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>Pellentesque accumsan cursus dui, sodales blandit urna sodales vitae Pellentesque accumsan cursus dui, sodales blandit urna urna sodales vitae ipsum Pellentesque accumsan cursus dui, sodales blan urna sodales vitaePellentesque accumsan cursus dui, sodales blan sodales vitae.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<div class=\"agileinfo-about-grid text-center\">\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-xs-6 w3ls-about-grid\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-stats\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t<h6>service1</h6>\r\n");
      out.write("\t\t\t\t\t<p>Itaque earum rerum hic tenetur asapi ente delectus \r\n");
      out.write("\t\t\t\t\t\treiciendis maiores alias sodales vitaePellentesque accum</p> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-xs-6 w3ls-about-grid about-2\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t<h6>service2</h6>\r\n");
      out.write("\t\t\t\t\t<p>Itaque earum rerum hic tenetur asapi ente delectus \r\n");
      out.write("\t\t\t\t\t\treiciendis maiores alias sodales vitaePellentesque accum</p> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-xs-6 w3ls-about-grid\">\r\n");
      out.write("\t\t\t\t\t<span class=\"fa fa-cogs\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t<h6>service2</h6>\r\n");
      out.write("\t\t\t\t\t<p>Itaque earum rerum hic tenetur asapi ente delectus \r\n");
      out.write("\t\t\t\t\t\treiciendis maiores alias sodales vitaePellentesque accum</p> \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\t\r\n");
      out.write("<!-- //about -->\r\n");
      out.write(" \r\n");
      out.write("<!-- travel -->\r\n");
      out.write("<div class=\"travel\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h4>Travel tourist</h4>\r\n");
      out.write("\t\t<h3>Better to see something once than hear about it a thousand times</h3>\r\n");
      out.write("\t\t<p>watch our video here</p>\r\n");
      out.write("\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t<a class=\"#\" data-toggle=\"modal\" data-target=\"#myModal1\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-play-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //travel -->\r\n");
      out.write("\r\n");
      out.write("<!-- popular packages -->\r\n");
      out.write("<div class=\"packages\" id=\"packages\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"wthree_head_section\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">Popular Packages</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"packages_grids\">\r\n");
      out.write("\t\t\t<div class=\"packages_grid1\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/package1.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t\t<h4>London Holiday Tour</h4>\r\n");
      out.write("\t\t\t\t\t<h5>900$</h5>\r\n");
      out.write("\t\t\t\t\t<a href=\"#small-dialog\" class=\"w3_agileits_sign_up2 popup-with-zoom-anim ab scroll\">Book Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"web/images/package2.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t\t<h4>Paris Eiffel Tower</h4>\r\n");
      out.write("\t\t\t\t\t<h5>290$</h5>\r\n");
      out.write("\t\t\t\t\t<a href=\"#small-dialog\" class=\"w3_agileits_sign_up2 popup-with-zoom-anim ab scroll\">Book Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"web/images/package3.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"packages_grid2\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"web/images/package6.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"web/images/package4.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t\t<h4>Thailand Summer Beach</h4>\r\n");
      out.write("\t\t\t\t\t<h5>850$</h5>\r\n");
      out.write("\t\t\t\t\t<a href=\"#small-dialog\" class=\"w3_agileits_sign_up2 popup-with-zoom-anim ab scroll\">Book Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 package1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"web/images/package5.jpg\" alt=\"package1\" />\r\n");
      out.write("\t\t\t\t\t<h4>Japan Imperial Museum</h4>\r\n");
      out.write("\t\t\t\t\t<h5>210$</h5>\r\n");
      out.write("\t\t\t\t\t<a href=\"#small-dialog\" class=\"w3_agileits_sign_up2 popup-with-zoom-anim ab scroll\">Book Now</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //popular packages -->\r\n");
      out.write(" \r\n");
      out.write("<!-- agile_testimonials -->\r\n");
      out.write("\t<div class=\"agile_testimonials\" id=\"testimonials\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"wthree_head_section\">\r\n");
      out.write("\t\t\t\t<h3 class=\"title\">testimonials</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"agile_wthree_inner_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"test-agile_main_section\">\r\n");
      out.write("\t\t\t\t\t<div id=\"owl-demo2\" class=\"owl-carousel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"web/images/1.jpg\" alt=\"\" class=\"img-r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>John Warner</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"para-w3-agile\">Lorem ipsum dolor sit amet, consectetur adipiscing elit,consectetur adipiscing elit, sed do eiusmod tempor incididunt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tut labore et dolore magna aliqua sed do eiusmod tempor incididunt ut labore etdolore magna aliqua. Ut enim ad minim\r\n");
      out.write("\t\t\t\t\t\t\t\t\tveniam, quis. Lorem ipsum dolor .</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"web/images/2.jpg\" alt=\"\" class=\"img-r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>Steve Warner</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"para-w3-agile\">Lorem ipsum dolor sit amet, consectetur adipiscing elit,consectetur adipiscing elit, sed do eiusmod tempor incididunt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tut labore et dolore magna aliqua sed do eiusmod tempor incididunt ut labore etdolore magna aliqua. Ut enim ad minim\r\n");
      out.write("\t\t\t\t\t\t\t\t\tveniam, quis. Lorem ipsum dolor .</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test-grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"web/images/3.jpg\" alt=\"\" class=\"img-r\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test-grid2_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>James Warner</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"para-w3-agile\">Lorem ipsum dolor sit amet, consectetur adipiscing elit,consectetur adipiscing elit, sed do eiusmod tempor incididunt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tut labore et dolore magna aliqua sed do eiusmod tempor incididunt ut labore etdolore magna aliqua. Ut enim ad minim\r\n");
      out.write("\t\t\t\t\t\t\t\t\tveniam, quis. Lorem ipsum dolor .</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-quote-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //agile_testimonials -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- stats -->\r\n");
      out.write("<div class=\"stats\" id=\"stats\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3 class=\"title\">Stats</h3>\r\n");
      out.write("\t\t<div class=\"agileits_stats_grids\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-xs-4 agileinfo_stats\">\r\n");
      out.write("\t\t\t\t<div class=\"agileinfo_stats_grid\">\r\n");
      out.write("\t\t\t\t\t<p class=\"counter\">654</p>\r\n");
      out.write("\t\t\t\t\t<h3>Travellers</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-xs-4 agileinfo_stats mid-w3l-stat\">\r\n");
      out.write("\t\t\t\t<div class=\"agileinfo_stats_grid\">\r\n");
      out.write("\t\t\t\t\t<p class=\"counter\">432</p>\r\n");
      out.write("\t\t\t\t\t<h3>Locations</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-xs-4 agileinfo_stats mid-w3l-stat\">\r\n");
      out.write("\t\t\t\t<div class=\"agileinfo_stats_grid\">\r\n");
      out.write("\t\t\t\t\t<p class=\"counter\">200</p>\r\n");
      out.write("\t\t\t\t\t<h3>Packages</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-xs-4 agileinfo_stats mid-w3l-stat\">\r\n");
      out.write("\t\t\t\t<div class=\"agileinfo_stats_grid\">\r\n");
      out.write("\t\t\t\t\t<p class=\"counter\">230</p>\r\n");
      out.write("\t\t\t\t\t<h3>Awards</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //stats -->\r\n");
      out.write("\r\n");
      out.write("<!-- contact -->\r\n");
      out.write("\t<div class=\"w3ls-section contact\" id=\"contact\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3ls-title\">\r\n");
      out.write("\t\t\t\t<h3 class=\"title\">get in touch</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_map\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48306.05339877067!2d-74.245183970742!3d40.825144655510556!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2555646a723a1%3A0x449f3366d017b214!2sMontclair%2C+NJ%2C+USA!5e0!3m2!1sen!2sin!4v1465991700675\"\r\n");
      out.write("\t\t\t\t    style=\"border:0\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"contact_wthreerow agileits-w3layouts\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7 w3l_contact_form\">\r\n");
      out.write("\t\t\t\t\t<h4>Contact Form</h4>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"Name\" value=\"Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Name';}\"\r\n");
      out.write("\t\t\t\t\t\t    required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" name=\"Email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\"\r\n");
      out.write("\t\t\t\t\t\t    required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"Phone\" value=\"Phone\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Phone';}\"\r\n");
      out.write("\t\t\t\t\t\t    required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Message\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Message...';}\" required=\"\">Message...</textarea>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5 agileits_w3layouts_contact_gridl\">\r\n");
      out.write("\t\t\t\t\t<div class=\"agileits_mail_grid_right_grid\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Contact Info</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur. Nunc id dui vitae urna tincidunt varius.</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact_info\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"fa fa-map-marker\" aria-hidden=\"true\"></span>1234k Avenue, 4th block,3FB,New Jersey.</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"fa fa-envelope\" aria-hidden=\"true\"></span><a href=\"mailto:info@example.com\">info@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"fa fa-phone\" aria-hidden=\"true\"></span>+1234 567 567</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //contact -->\r\n");
      out.write(" \r\n");
      out.write("<!-- footer start here -->\r\n");
      out.write("<div class=\"footer-agile\">\r\n");
      out.write("\t<!-- newsletter -->\r\n");
      out.write("\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t<div class=\"agile-leftmk\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" placeholder=\"Enter Your Email Address\" name=\"email\" required=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Subscribe\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- //newsletter -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-btm-agileinfo\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-xs-3 footer-grid w3social\">\r\n");
      out.write("\t\t\t\t\t<h3>About us</h3>\r\n");
      out.write("\t\t\t\t\t<p class=\"footer-p1\">Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Proin sed ligula \r\n");
      out.write("\t\t\t\t\tac metus finibus hendrerit sed at libero. Praesent reiciendis voluptatibus maiores alias.</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">read more <span class=\"fa fa-long-arrow-right\"></span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-xs-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t<h3>Contact Info</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"fa fa-phone\"></i>+012 345 6789</li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"fa fa-fax\"></i>+987 654 3210</li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"fa fa-map-marker\"></i>Kmome St, NY 10002, Canada.</li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"fa fa-envelope-o\"></i><a href=\"mailto:example@mail.com\">mail@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"fa fa-envelope-o\"></i><a href=\"mailto:example@mail.com\">mail1@example1.com</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-xs-3 footer-grid w3social\">\r\n");
      out.write("\t\t\t\t\t<h3>Quick Links</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#about\" class=\"scroll\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#packages\" class=\"scroll\">Packages</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#testimonials\" class=\"scroll\">Happy Customers</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#contact\" class=\"scroll\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-xs-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t<h3>Latest Tweets</h3>\r\n");
      out.write("\t\t\t\t\t<ul class=\"tweet-agile\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-twitter-square\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tweet-p1\"><a href=\"mailto:support@company.com\">@example</a> sit amet consectetur adipiscing. <a href=\"#\">http://ax.by/zzzz</a></p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tweet-p2\">Posted 3 days ago.</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-twitter-square\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tweet-p1\"><a href=\"mailto:support@company.com\">@example</a> sit amet consectetur adipiscing. <a href=\"#\">http://cx.dy/zzzz</a></p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tweet-p2\">Posted 3 days ago.</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-agilem\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-8 col-xs-9 copy-w3lsright\">\r\n");
      out.write("\t\t\t\t\t<p>Â© 2017 Tourist. All rights reserved | Design by <a href=\"http://w3layouts.com\"> W3layouts.</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4 col-xs-3 social-w3licon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-button twitter\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-button facebook\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-button google\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-button dribbble\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //footer end here -->\r\n");
      out.write("\r\n");
      out.write("<!-- popup signup form -->\r\n");
      out.write("\t<div class=\"wthree_pop_up\"> \r\n");
      out.write("\t\t<div id=\"small-dialog\" class=\"mfp-hide agile_signup_form\">\r\n");
      out.write("\t\t\t<h2>BOOK OUR TRAVEL TOURIST</h2>\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-control\"> \r\n");
      out.write("\t\t\t\t\t<label class=\"header1\">Traveller Name <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"firstname\" name=\"firstname\" placeholder=\"Full Name\" title=\"Please enter your Full Name\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t<label class=\"editContent\">Travel Location <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>London</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Paris</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>India</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Japan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>America</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\t\r\n");
      out.write("\t\t\t\t\t<label class=\"header1\">Email Address <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"mail@example.com\" title=\"Please enter a valid email\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\t\r\n");
      out.write("\t\t\t\t\t<label class=\"header1\">Phone Number <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"tel\" id=\"tel\" name=\"tel\" placeholder=\"Phone number\" title=\"Please enter a valid Phone number\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\t\r\n");
      out.write("\t\t\t\t\t<label class=\"editContent\">Journey start date <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t<input class=\"date has Datepicker\" id=\"datepicker\" name=\"Text\" type=\"text\" value=\"Start Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '21/11/2017';}\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\t\r\n");
      out.write("\t\t\t\t\t<label class=\"editContent\">Journey return date <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t<input class=\"date has Datepicker\" id=\"datepicker\" name=\"Text\" type=\"text\" value=\"Return Date\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '21/11/2017';}\" required=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t<label class=\"editContent\">No: of travellers <span>:</span></label>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>5 or more</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"w3_submit\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"register\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = function () {\r\n");
      out.write("\t\t\tdocument.getElementById(\"password1\").onchange = validatePassword;\r\n");
      out.write("\t\t\tdocument.getElementById(\"password2\").onchange = validatePassword;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction validatePassword(){\r\n");
      out.write("\t\t\tvar pass2=document.getElementById(\"password2\").value;\r\n");
      out.write("\t\t\tvar pass1=document.getElementById(\"password1\").value;\r\n");
      out.write("\t\t\tif(pass1!=pass2)\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"password2\").setCustomValidity(\"Passwords Don't Match\");\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"password2\").setCustomValidity('');\t \r\n");
      out.write("\t\t\t\t//empty string means no validation error\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //popup signup form -->\r\n");
      out.write("\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"web/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("\r\n");
      out.write("<!-- Stats-Number-Scroller-Animation-JavaScript -->\r\n");
      out.write("<script src=\"web/js/waypoints.min.js\"></script> \r\n");
      out.write("<script src=\"web/js/counterup.min.js\"></script> \r\n");
      out.write("<script>\r\n");
      out.write("\tjQuery(document).ready(function( $ ) {\r\n");
      out.write("\t\t$('.counter').counterUp({\r\n");
      out.write("\t\t\tdelay: 10,\r\n");
      out.write("\t\t\ttime: 1000 \r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- //Stats-Number-Scroller-Animation-JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<!-- Calendar -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"web/css/jquery-ui.css\" />\r\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$( \"#datepicker,#datepicker1\" ).datepicker();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //Calendar -->\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- for banner js file-->\r\n");
      out.write("<script src=\"web/js/poposlides.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".slides\").poposlides();\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //for banner js file-->\r\n");
      out.write("\r\n");
      out.write("<!-- pop-up-box -->\r\n");
      out.write("\t\t<script src=\"web/js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\t\t\t\ttype: 'inline',\r\n");
      out.write("\t\t\t\t\tfixedContentPos: false,\r\n");
      out.write("\t\t\t\t\tfixedBgPos: true,\r\n");
      out.write("\t\t\t\t\toverflowY: 'auto',\r\n");
      out.write("\t\t\t\t\tcloseBtnInside: true,\r\n");
      out.write("\t\t\t\t\tpreloader: false,\r\n");
      out.write("\t\t\t\t\tmidClick: true,\r\n");
      out.write("\t\t\t\t\tremovalDelay: 300,\r\n");
      out.write("\t\t\t\t\tmainClass: 'my-mfp-zoom-in'\r\n");
      out.write("\t\t\t\t});\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!--//pop-up-box -->\r\n");
      out.write("\r\n");
      out.write("<!-- requried-jsfiles-for owl -->\t<!-- testimonials -->\r\n");
      out.write("\t<script src=\"web/js/owl.carousel.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t$(\"#owl-demo2\").owlCarousel({\r\n");
      out.write("\t\t\t\titems: 1,\r\n");
      out.write("\t\t\t\tlazyLoad: false,\r\n");
      out.write("\t\t\t\tautoPlay: true,\r\n");
      out.write("\t\t\t\tnavigation: false,\r\n");
      out.write("\t\t\t\tnavigationText: false,\r\n");
      out.write("\t\t\t\tpagination: true,\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //requried-jsfiles-for owl -->\t<!-- //testimonials -->\r\n");
      out.write("\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"web/js/move-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"web/js/easing.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(document).ready(function ($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function (event) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\t\tscrollTop: $(this.hash).offset().top\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- here stars scrolling icon -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("\r\n");
      out.write("<!-- Scrolling Nav JavaScript --> \r\n");
      out.write("    <script src=\"web/js/scrolling-nav.js\"></script>  \r\n");
      out.write("<!-- //fixed-scroll-nav-js --> \r\n");
      out.write("\t\t\r\n");
      out.write("<!-- for bootstrap working -->\r\n");
      out.write("\t<script src=\"web/js/bootstrap.js\"></script>\r\n");
      out.write("<!-- //for bootstrap working -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
